### PR TITLE
Export all symbols on windows by default

### PR DESCRIPTION
**Pull request by asmw**
without adding explicit __declspecs

See: https://cmake.org/cmake/help/v3.4/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html#prop_tgt:WINDOWS_EXPORT_ALL_SYMBOLS

From the docs it seems to require a CMake minversion bump to work.

### CODE REVIEW

**Comment by alecthomas** [comment]
Hi, this is failing CI due to to Travis' old version of CMake.

**Comment by asmw** [comment]
Since I guess MSVC + CMake < 3.4 + shared build ist the only problematic case I guess this should do.

**Comment by asmw** [comment]
Can you set up a shared appveyor build?

**Comment by asmw** [comment]
This needs work...

**Comment by alecthomas** [comment]
Cross-platform is a PITA :(

**Comment by asmw** [comment]
Yup. If you're interested, the branch in my repo now
- builds shared but fails entity tests, all other tests pass
- has an appveyor matrix config for shared/static

**Pull request closed without merging**
