### PR TITLE
Fixed shared library compilation and Function to retrieve the entity from ComponentHandle

### PR DESCRIPTION
**Pull request by roig**
- Added a function to retrieve the Entity associated with a component in ComponentHandle.
- Fixed that when ENTITYX_BUILD_SHARED=1 was compiling the static library and the shared_library. Now it only compiles one of them, shared or static, but not both. Using visual studio compiler, now, the shared library doesn't create a .lib file (because it doesn't export anything which is OK).

### CODE REVIEW

**Comment by alecthomas** [comment]
I'm not sure if you get notified, but this isn't passing the tests.

**Comment by roig** [comment]
Hello Alecthomas,
The problem that I fixed will make the tests on windows to always fail. But this is OK, because before my fix, when you configured cmake with:  ENTITYX_BUILD_SHARED=1 it was compiling the static
library and the shared_library. Now it only compiles one of them, shared or static, but not both. Using visual studio compiler, now, the shared library doesn't create a .lib file (because it doesn't export anything which is OK). 

So the tests were linked with the static library not the shared one and when you build the static library in Windows all the symbols are exported, this is the reason that all the tests were linking ok.
But now, with the problem fixed, only the shared library is created.

In GCC and CLANG all will work ok, because they export all the symbols when building a shared library.

Resume: Entityx shared library never worked in Windows (visual c) because there aren't any exported class/method. A workaround is to change the appveyor to compile the static library. Then start the work to implement the class/functions exporting to support a shared library on windows.

Sorry for my english!

**Comment by alecthomas** [comment]
Fixed!

**Comment by alecthomas** [comment]
Thanks for the PR!

**Pull request merged**
