### PR TITLE
Fix C++11 feature checking for Microsoft Visual C++ Build Tools 2015

### PR DESCRIPTION
**Pull request by jarrettchisholm**
Specifically, I get these errors when I attempt to build the project with CMake:

```
PS C:\Users\jarrett\projects\entityx3\build> cmake -G "Visual Studio 14" -DENTITYX_BUILD_SHARED=0 ..
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- EntityX version 1.1.2
-- Checking C++11 support for "auto" (N2546)
-- Checking C++11 support for "auto" (N2546) -- not supported
-- Checking C++11 support for "nullptr" (N2431)
-- Checking C++11 support for "nullptr" (N2431) -- not supported
-- Checking C++11 support for "lambda" (N2927)
-- Checking C++11 support for "lambda" (N2927) -- not supported
-- Checking C++11 support for "static_assert" (N1720)
-- Checking C++11 support for "static_assert" (N1720) -- not supported
-- Checking C++11 support for "rvalue_references" (N2118)
-- Checking C++11 support for "rvalue_references" (N2118) -- not supported
-- Checking C++11 support for "decltype" (N2343)
-- Checking C++11 support for "decltype" (N2343) -- not supported
-- Checking C++11 support for "cstdint"
-- Checking C++11 support for "cstdint" -- not supported
-- Checking C++11 support for "long_long" (N1811)
-- Checking C++11 support for "long_long" (N1811) -- not supported
-- Checking C++11 support for "variadic_templates" (N2555)
-- Checking C++11 support for "variadic_templates" (N2555) -- not supported
-- Checking C++11 support for "constexpr" (N2235)
-- Checking C++11 support for "constexpr" (N2235) -- not supported
-- Checking C++11 support for "sizeof_member" (N2253)
-- Checking C++11 support for "sizeof_member" (N2253) -- not supported
-- Checking C++11 support for "__func__" (N2340)
-- Checking C++11 support for "__func__" (N2340) -- not supported
-- Performing Test ENTITYX_HAVE_CXX11_STDLIB
-- Performing Test ENTITYX_HAVE_CXX11_STDLIB - Success
-- -- Using -stdlib=libc++
-- Looking for stdint.h
-- Looking for stdint.h - found
-- -- Defaulting to release build (use -DCMAKE_BUILD_TYPE:STRING=Debug for debug build)
-- -- Checking C++ features
CMake Error at CMakeLists.txt:88 (message):
  C++11 auto support required -- FALSE
Call Stack (most recent call first):
  CMakeLists.txt:119 (require)


-- Configuring incomplete, errors occurred!
See also "C:/Users/jarrett/projects/entityx3/build/CMakeFiles/CMakeOutput.log".
```

### CODE REVIEW

**Comment by jarrettchisholm** [comment]
The CMake file might work for Visual Studio 2015 proper, but for the build tools it seems to fail.

**Comment by alecthomas** [comment]
There seem to be a few unnecessary changes here. If you're fixing a bug can you narrow it down to just that please?

**Comment by jarrettchisholm** [comment]
I'm afraid it's more or less all necessary.

I will annotate the code with the reasoning.

**Comment by roig** [comment]
Maybe you should get rid of those checks. Now all compilers that have C++11 support should have those features. I think it's not necessary to check for them in cmake.

**Comment by jarrettchisholm** [comment]
@roig I agree, I was just trying to maintain the status-quo of the CMake file while making the checks use more 'modern' CMake features.

If we're in agreement I don't mind removing them.

**Comment by jarrettchisholm** [comment]
Sorry for the delay @alecthomas!  I made the comments that day but I guess I needed to 'review' them or something :)

**Comment by alecthomas** [comment]
Thanks!

**Pull request merged**
